branches:
  - master
  - release-drafter  # for testing edits to this configuration

name-template: 'Version $NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'

sort-by: title # sort alphabetically
sort-direction: ascending

categories:
  - title: '### NEU:'
    labels:
      - 'pr/feature'
  - title: '### REPARIERT:'
    labels:
      - 'pr/bug-fix'
  - title: '### VERBESSERT:'
    labels:
      - 'pr/enhancement'
      - 'pr/optimization'
  - title: '### VERÄNDERT:'
    labels:
      - 'pr/cleanup'
      - 'pr/change'
  - title: '### EINSTELLUNGEN:'
    labels:
      - 'pr/setting'
  - title: '### ÜBERSETZUNGEN:'
    labels:
      - 'pr/translation'
  - title: '## DOKUMENTATION:'
    labels:
      - 'pr/documentation'

exclude-labels:
  - 'ignore-changelog'
  - 'tools'

change-template: '* $TITLE (#$NUMBER) by $AUTHOR'
template: |
  _Requires the latest Version of [CBA](https://github.com/CBATeam/CBA_A3) and [ACE](https://github.com/acemod/ACE3)._

  ## Zusammenfassung

  

  ## Änderungsprotokoll 

  $CHANGES

  ## Mitwirkende

  $CONTRIBUTORS

replacers:
  # Category titles
  # Der Release Drafter macht die Kategorie automaischt als ## Heading
  # und wir wollen sie als ### Heading haben
  - search: '\#\# (\#\#\# (NEU|REPARIERT|VERBESSERT|VERÄNDERT|EINSTELLUNGEN|ÜBERSETZUNGEN|DOKUMENTATION):)/g'
    replace: '$1'